export type FoodItem = {
  id: string
  type: 'system' | 'user'
  name_sr: string
  search_name: string
  category_id: string
  icon?: string
  calories_kcal: number
  protein_g: number
  carbs_g: number
  fat_g: number
  serving_g?: number       // gram weight of one serving (e.g. 30 for whey scoop)
  serving_label?: string   // label for one serving (e.g. 'merica')
}

export const CATEGORIES = [
  { id: 'cat-meso',      name: 'Meso',                icon: '🥩' },
  { id: 'cat-riba',      name: 'Riba',                icon: '🐟' },
  { id: 'cat-jaja',      name: 'Jaja',                icon: '🥚' },
  { id: 'cat-mlecni',   name: 'Mlečni',              icon: '🥛' },
  { id: 'cat-supp',      name: 'Suplementi',          icon: '💊' },
  { id: 'cat-zitarice',  name: 'Žitarice',            icon: '🌾' },
  { id: 'cat-hleb',      name: 'Hleb & Tortilje',     icon: '🍞' },
  { id: 'cat-krompir',   name: 'Krompir & Mahunarke', icon: '🥔' },
  { id: 'cat-voce',      name: 'Voće',                icon: '🍎' },
  { id: 'cat-povrce',    name: 'Povrće',              icon: '🥦' },
  { id: 'cat-ulja',      name: 'Ulja',                icon: '🫙' },
  { id: 'cat-orasasti',  name: 'Orašasti plodovi',    icon: '🥜' },
  { id: 'cat-semenke',   name: 'Semenke',             icon: '🌱' },
  { id: 'cat-ostalo',    name: 'Ostalo',              icon: '🍽️' },
]

export const SYSTEM_FOODS: FoodItem[] = [

  // ── JAJA ─────────────────────────────────────────────────────────────────────
  { id:'sf-jaje-celo',    type:'system', category_id:'cat-jaja',    name_sr:'Jaje',                             search_name:'jaje celo komad',                        calories_kcal:140,  protein_g:12.5, carbs_g:0.7, fat_g:10,   serving_g:50, serving_label:'kom' },

  // ── MESO ─────────────────────────────────────────────────────────────────────
  { id:'sf-piletina-grudi',      type:'system', category_id:'cat-meso', name_sr:'Piletina (grudi, sirova)',          search_name:'piletina grudi sirova pilece prsa',      calories_kcal:120, protein_g:23,   carbs_g:0,   fat_g:2.6  },
  { id:'sf-piletina-batak',      type:'system', category_id:'cat-meso', name_sr:'Piletina (batak)',                  search_name:'piletina batak sirov',                   calories_kcal:184, protein_g:24,   carbs_g:0,   fat_g:9    },
  { id:'sf-piletina-karabatak',  type:'system', category_id:'cat-meso', name_sr:'Piletina (karabatak)',              search_name:'piletina karabatak sirov',               calories_kcal:187, protein_g:19,   carbs_g:0,   fat_g:8    },
  { id:'sf-pileca-dzigerica',    type:'system', category_id:'cat-meso', name_sr:'Pileća džigerica',                  search_name:'pileca dzigerica',                       calories_kcal:119, protein_g:17,   carbs_g:2,   fat_g:4.8  },
  { id:'sf-piletina-krilca',     type:'system', category_id:'cat-meso', name_sr:'Piletina (krilca)',                 search_name:'piletina krilca',                        calories_kcal:190, protein_g:18,   carbs_g:0,   fat_g:14   },
  { id:'sf-pilece-prsa-dimljene',type:'system', category_id:'cat-meso', name_sr:'Pileće prsa (dimljene)',            search_name:'pilece prsa dimljene',                   calories_kcal:80,  protein_g:15,   carbs_g:2,   fat_g:1    },
  { id:'sf-junetina-nemasna',    type:'system', category_id:'cat-meso', name_sr:'Junetina (nemasna)',                search_name:'junetina nemasna',                       calories_kcal:142, protein_g:21,   carbs_g:0,   fat_g:5    },
  { id:'sf-junetina-masnija',    type:'system', category_id:'cat-meso', name_sr:'Junetina (masnija)',                search_name:'junetina masnija govedina',              calories_kcal:187, protein_g:25,   carbs_g:0,   fat_g:10   },
  { id:'sf-govedina-but',        type:'system', category_id:'cat-meso', name_sr:'Govedina (but)',                    search_name:'govedina but',                           calories_kcal:190, protein_g:24,   carbs_g:0,   fat_g:10   },
  { id:'sf-govedina-file',       type:'system', category_id:'cat-meso', name_sr:'Govedina (file)',                   search_name:'govedina file',                          calories_kcal:175, protein_g:23,   carbs_g:0,   fat_g:4    },
  { id:'sf-govedina-rebra',      type:'system', category_id:'cat-meso', name_sr:'Govedina (rebra)',                  search_name:'govedina rebra',                         calories_kcal:297, protein_g:21,   carbs_g:0,   fat_g:25   },
  { id:'sf-teletina-but',        type:'system', category_id:'cat-meso', name_sr:'Teletina (but)',                    search_name:'teletina but',                           calories_kcal:150, protein_g:22,   carbs_g:0,   fat_g:6    },
  { id:'sf-teletina-plecka',     type:'system', category_id:'cat-meso', name_sr:'Teletina (plećka)',                 search_name:'teletina plecka',                        calories_kcal:165, protein_g:21,   carbs_g:0,   fat_g:8    },
  { id:'sf-svinjska-plecka',     type:'system', category_id:'cat-meso', name_sr:'Svinjska plećka',                   search_name:'svinjska plecka',                        calories_kcal:240, protein_g:21,   carbs_g:0,   fat_g:18   },
  { id:'sf-svinjski-file',       type:'system', category_id:'cat-meso', name_sr:'Svinjski file',                     search_name:'svinjski file',                          calories_kcal:120, protein_g:22,   carbs_g:0,   fat_g:2    },
  { id:'sf-svinjski-kare',       type:'system', category_id:'cat-meso', name_sr:'Svinjski kare',                     search_name:'svinjski kare kotlet',                   calories_kcal:180, protein_g:22,   carbs_g:0,   fat_g:9    },
  { id:'sf-svinjski-vrat',       type:'system', category_id:'cat-meso', name_sr:'Svinjski vrat',                     search_name:'svinjski vrat',                          calories_kcal:250, protein_g:20,   carbs_g:0,   fat_g:20   },
  { id:'sf-curetina-file',       type:'system', category_id:'cat-meso', name_sr:'Ćuretina (file)',                   search_name:'curetina file belo meso',                calories_kcal:135, protein_g:29,   carbs_g:0,   fat_g:1    },
  { id:'sf-curetina-batak',      type:'system', category_id:'cat-meso', name_sr:'Ćuretina (batak)',                  search_name:'curetina batak',                         calories_kcal:157, protein_g:20,   carbs_g:0,   fat_g:9    },
  { id:'sf-curetina-karabatak',  type:'system', category_id:'cat-meso', name_sr:'Ćuretina (karabatak)',              search_name:'curetina karabatak',                     calories_kcal:165, protein_g:21,   carbs_g:0,   fat_g:10   },
  { id:'sf-cureca-krilca',       type:'system', category_id:'cat-meso', name_sr:'Ćureća krilca',                    search_name:'cureca krilca',                          calories_kcal:190, protein_g:19,   carbs_g:0,   fat_g:13   },
  { id:'sf-kulen',               type:'system', category_id:'cat-meso', name_sr:'Kulen',                             search_name:'kulen',                                  calories_kcal:370, protein_g:22,   carbs_g:1,   fat_g:32   },
  { id:'sf-pecenica',            type:'system', category_id:'cat-meso', name_sr:'Pečenica',                          search_name:'pecenica suva',                          calories_kcal:198, protein_g:27,   carbs_g:0,   fat_g:10   },
  { id:'sf-panceta',             type:'system', category_id:'cat-meso', name_sr:'Pančeta',                           search_name:'panceta slanina',                        calories_kcal:393, protein_g:17,   carbs_g:1,   fat_g:35   },
  { id:'sf-prsuta',              type:'system', category_id:'cat-meso', name_sr:'Pršuta (sušena)',                   search_name:'prsuta susena',                          calories_kcal:269, protein_g:25.3, carbs_g:0,   fat_g:18.3 },
  { id:'sf-slanina',             type:'system', category_id:'cat-meso', name_sr:'Slanina (sirova)',                  search_name:'slanina sirova',                         calories_kcal:541, protein_g:12,   carbs_g:0,   fat_g:53   },
  { id:'sf-jagnjetina-but',      type:'system', category_id:'cat-meso', name_sr:'Jagnjetina (but)',                  search_name:'jagnjetina but',                         calories_kcal:206, protein_g:20,   carbs_g:0,   fat_g:14   },
  { id:'sf-jagnjetina-rebra',    type:'system', category_id:'cat-meso', name_sr:'Jagnjetina (rebra)',                search_name:'jagnjetina rebra',                       calories_kcal:292, protein_g:18,   carbs_g:0,   fat_g:24   },
  { id:'sf-jaretina',            type:'system', category_id:'cat-meso', name_sr:'Jaretina',                          search_name:'jaretina jare',                          calories_kcal:122, protein_g:21,   carbs_g:0,   fat_g:3.6  },
  { id:'sf-zecetina',            type:'system', category_id:'cat-meso', name_sr:'Zečetina',                          search_name:'zecetina zec',                           calories_kcal:114, protein_g:21,   carbs_g:0,   fat_g:2.3  },
  { id:'sf-srnetina',            type:'system', category_id:'cat-meso', name_sr:'Srnetina (divljač)',                search_name:'srnetina divljac',                       calories_kcal:120, protein_g:22,   carbs_g:0,   fat_g:2.4  },
  { id:'sf-vepretina',           type:'system', category_id:'cat-meso', name_sr:'Vepretina (divlja svinja)',         search_name:'vepretina divlja svinja',                calories_kcal:107, protein_g:21,   carbs_g:0,   fat_g:2.1  },
  { id:'sf-patka',               type:'system', category_id:'cat-meso', name_sr:'Patka (file, bez kože)',            search_name:'patka file bez koze',                    calories_kcal:201, protein_g:19,   carbs_g:0,   fat_g:11   },
  { id:'sf-guska',               type:'system', category_id:'cat-meso', name_sr:'Guska (file)',                      search_name:'guska file',                             calories_kcal:238, protein_g:16,   carbs_g:0,   fat_g:19   },
  { id:'sf-prepelica',           type:'system', category_id:'cat-meso', name_sr:'Prepelica',                         search_name:'prepelica',                              calories_kcal:134, protein_g:25,   carbs_g:0,   fat_g:3.3  },
  { id:'sf-dzigeri-govedja',     type:'system', category_id:'cat-meso', name_sr:'Goveđa džigerica',                  search_name:'govedja dzigerica jetra',                calories_kcal:135, protein_g:20,   carbs_g:3.9, fat_g:3.6  },
  { id:'sf-bubrezii',            type:'system', category_id:'cat-meso', name_sr:'Bubrezi (goveđi)',                  search_name:'bubrezi govedji',                        calories_kcal:99,  protein_g:17,   carbs_g:0.3, fat_g:3.1  },
  { id:'sf-srce',                type:'system', category_id:'cat-meso', name_sr:'Srce (goveđe)',                     search_name:'srce govedje',                           calories_kcal:112, protein_g:17,   carbs_g:0.1, fat_g:4    },
  { id:'sf-mlevena-piletina',    type:'system', category_id:'cat-meso', name_sr:'Mlevena piletina',                  search_name:'mlevena piletina',                       calories_kcal:143, protein_g:17,   carbs_g:0,   fat_g:8    },
  { id:'sf-mlevena-junetina',    type:'system', category_id:'cat-meso', name_sr:'Mlevena junetina',                  search_name:'mlevena junetina govedina',              calories_kcal:254, protein_g:17,   carbs_g:0,   fat_g:20   },
  { id:'sf-mlevena-svinjetina',  type:'system', category_id:'cat-meso', name_sr:'Mlevena svinjetina',               search_name:'mlevena svinjetina',                     calories_kcal:297, protein_g:16,   carbs_g:0,   fat_g:26   },
  { id:'sf-hrenovke',            type:'system', category_id:'cat-meso', name_sr:'Hrenovke',                          search_name:'hrenovke virsle',                        calories_kcal:290, protein_g:11,   carbs_g:2,   fat_g:26   },
  { id:'sf-suncica',             type:'system', category_id:'cat-meso', name_sr:'Šunka (kuvana)',                    search_name:'sunka kuvana',                           calories_kcal:145, protein_g:17,   carbs_g:2,   fat_g:7    },
  { id:'sf-parizer',             type:'system', category_id:'cat-meso', name_sr:'Parizer / Mortadela',               search_name:'parizer mortadela',                      calories_kcal:310, protein_g:13,   carbs_g:2,   fat_g:28   },

  // ── RIBA ─────────────────────────────────────────────────────────────────────
  { id:'sf-tunjevina-konz',      type:'system', category_id:'cat-riba', name_sr:'Tunjevina (konzerva u vodi)',       search_name:'tunjevina konzerva voda tuna',           calories_kcal:116, protein_g:26,   carbs_g:0,   fat_g:1    },
  { id:'sf-tuna-sirova',         type:'system', category_id:'cat-riba', name_sr:'Tuna (sirova)',                     search_name:'tuna sirova',                            calories_kcal:132, protein_g:23,   carbs_g:0,   fat_g:1    },
  { id:'sf-saran',               type:'system', category_id:'cat-riba', name_sr:'Šaran',                             search_name:'saran',                                  calories_kcal:131, protein_g:18,   carbs_g:0,   fat_g:6    },
  { id:'sf-oslic',               type:'system', category_id:'cat-riba', name_sr:'Oslić',                             search_name:'oslic sirov',                            calories_kcal:88,  protein_g:19,   carbs_g:0,   fat_g:1    },
  { id:'sf-brancin',             type:'system', category_id:'cat-riba', name_sr:'Brancin',                           search_name:'brancin',                                calories_kcal:97,  protein_g:20,   carbs_g:0,   fat_g:2    },
  { id:'sf-orada',               type:'system', category_id:'cat-riba', name_sr:'Orada',                             search_name:'orada',                                  calories_kcal:96,  protein_g:19,   carbs_g:0,   fat_g:2.5  },
  { id:'sf-lignje',              type:'system', category_id:'cat-riba', name_sr:'Lignje',                            search_name:'lignje morski plodovi',                  calories_kcal:92,  protein_g:16,   carbs_g:1.5, fat_g:1.4  },
  { id:'sf-skampi',              type:'system', category_id:'cat-riba', name_sr:'Škampi',                            search_name:'skampi gambori',                         calories_kcal:99,  protein_g:24,   carbs_g:0,   fat_g:0.3  },
  { id:'sf-losos',               type:'system', category_id:'cat-riba', name_sr:'Losos (sirov)',                     search_name:'losos sirov',                            calories_kcal:206, protein_g:20,   carbs_g:0,   fat_g:12   },
  { id:'sf-skusa',               type:'system', category_id:'cat-riba', name_sr:'Skuša (sirova)',                    search_name:'skusa sirova',                           calories_kcal:208, protein_g:20,   carbs_g:0,   fat_g:13   },
  { id:'sf-pastrmka',           type:'system', category_id:'cat-riba', name_sr:'Pastrmka',                           search_name:'pastrmka',                               calories_kcal:119, protein_g:20,   carbs_g:0,   fat_g:3.5  },
  { id:'sf-som',                type:'system', category_id:'cat-riba', name_sr:'Som',                                search_name:'som riba',                               calories_kcal:95,  protein_g:16,   carbs_g:0,   fat_g:2.8  },
  { id:'sf-amur',               type:'system', category_id:'cat-riba', name_sr:'Amur (bela riba)',                  search_name:'amur bela riba',                         calories_kcal:88,  protein_g:17,   carbs_g:0,   fat_g:1.8  },
  { id:'sf-deverika',           type:'system', category_id:'cat-riba', name_sr:'Deverika',                          search_name:'deverika riba',                          calories_kcal:105, protein_g:17,   carbs_g:0,   fat_g:4    },
  { id:'sf-stuka',              type:'system', category_id:'cat-riba', name_sr:'Štuka',                             search_name:'stuka riba',                             calories_kcal:88,  protein_g:19,   carbs_g:0,   fat_g:0.7  },
  { id:'sf-haringa',            type:'system', category_id:'cat-riba', name_sr:'Haringa',                           search_name:'haringa riba',                           calories_kcal:158, protein_g:18,   carbs_g:0,   fat_g:9    },
  { id:'sf-sardina',            type:'system', category_id:'cat-riba', name_sr:'Sardina (sveža)',                   search_name:'sardina riba',                           calories_kcal:208, protein_g:25,   carbs_g:0,   fat_g:11   },
  { id:'sf-incan',              type:'system', category_id:'cat-riba', name_sr:'Inćun / Anšova',                   search_name:'incan ansova',                           calories_kcal:210, protein_g:29,   carbs_g:0,   fat_g:10   },
  { id:'sf-dagnje',             type:'system', category_id:'cat-riba', name_sr:'Dagnje',                            search_name:'dagnje skoljke',                         calories_kcal:86,  protein_g:12,   carbs_g:3.7, fat_g:2.2  },
  { id:'sf-hobotnica',          type:'system', category_id:'cat-riba', name_sr:'Hobotnica',                         search_name:'hobotnica',                              calories_kcal:82,  protein_g:15,   carbs_g:2.2, fat_g:1    },
  { id:'sf-jesetrina',          type:'system', category_id:'cat-riba', name_sr:'Jesetra (kavijar riba)',            search_name:'jesetra',                                calories_kcal:135, protein_g:16,   carbs_g:0,   fat_g:7    },
  { id:'sf-tuna-ulje',          type:'system', category_id:'cat-riba', name_sr:'Tunjevina (konzerva u ulju)',       search_name:'tunjevina konzerva ulje',                calories_kcal:198, protein_g:25,   carbs_g:0,   fat_g:11   },

  // ── MLEČNI PROIZVODI ─────────────────────────────────────────────────────────
  { id:'sf-grcki-jogurt',        type:'system', category_id:'cat-mlecni', name_sr:'Grčki jogurt (2% m.m.)',          search_name:'grcki jogurt',                           calories_kcal:60,  protein_g:10,   carbs_g:3.5, fat_g:2    },
  { id:'sf-mleko',               type:'system', category_id:'cat-mlecni', name_sr:'Mleko (1.5% m.m.)',               search_name:'mleko kravlje',                          calories_kcal:45,  protein_g:3.4,  carbs_g:4.8, fat_g:1.5  },
  { id:'sf-skyr',                type:'system', category_id:'cat-mlecni', name_sr:'Skyr',                            search_name:'skyr sir',                               calories_kcal:63,  protein_g:11,   carbs_g:4,   fat_g:0.2  },
  { id:'sf-nemasni-sir',         type:'system', category_id:'cat-mlecni', name_sr:'Nemasni sir',                     search_name:'nemasni sir beli svezi',                 calories_kcal:96,  protein_g:17,   carbs_g:3,   fat_g:2    },
  { id:'sf-mladi-sir',           type:'system', category_id:'cat-mlecni', name_sr:'Mladi sir',                       search_name:'mladi sir svezi',                        calories_kcal:98,  protein_g:12,   carbs_g:3,   fat_g:4    },
  { id:'sf-trapist',             type:'system', category_id:'cat-mlecni', name_sr:'Trapist sir',                     search_name:'trapist sir',                            calories_kcal:357, protein_g:25,   carbs_g:1,   fat_g:29   },
  { id:'sf-feta',                type:'system', category_id:'cat-mlecni', name_sr:'Feta sir',                        search_name:'feta sir',                               calories_kcal:264, protein_g:14,   carbs_g:4,   fat_g:21   },
  { id:'sf-mozzarella',          type:'system', category_id:'cat-mlecni', name_sr:'Mozzarella',                      search_name:'mozzarella mocarela',                    calories_kcal:280, protein_g:18,   carbs_g:3,   fat_g:22   },
  { id:'sf-light-mozzarella',    type:'system', category_id:'cat-mlecni', name_sr:'Light mozzarella',                search_name:'light mozzarella mocarela',              calories_kcal:170, protein_g:21,   carbs_g:1.5, fat_g:8.5  },
  { id:'sf-ricotta',             type:'system', category_id:'cat-mlecni', name_sr:'Ricotta sir (light)',             search_name:'ricotta sir light',                      calories_kcal:130, protein_g:11,   carbs_g:7,   fat_g:3    },
  { id:'sf-edamer',              type:'system', category_id:'cat-mlecni', name_sr:'Edamer / Gauda',                  search_name:'edamer gauda sir',                       calories_kcal:340, protein_g:25,   carbs_g:2,   fat_g:27   },
  { id:'sf-cottage',             type:'system', category_id:'cat-mlecni', name_sr:'Cottage sir',                     search_name:'cottage sir skuta',                      calories_kcal:96,  protein_g:12,   carbs_g:3.8, fat_g:4.2  },
  { id:'sf-parmezan',            type:'system', category_id:'cat-mlecni', name_sr:'Parmezan',                        search_name:'parmezan parmigiano',                    calories_kcal:430, protein_g:41,   carbs_g:3.5, fat_g:27   },
  { id:'sf-krem-sir',            type:'system', category_id:'cat-mlecni', name_sr:'Krem sir',                        search_name:'krem sir philadelphia',                  calories_kcal:200, protein_g:5,    carbs_g:3,   fat_g:17   },
  { id:'sf-ella-sir',            type:'system', category_id:'cat-mlecni', name_sr:'Ella sir (light)',                search_name:'ella sir light nemasni',                 calories_kcal:70,  protein_g:13,   carbs_g:4.2, fat_g:0.5  },
  { id:'sf-tofu',                type:'system', category_id:'cat-mlecni', name_sr:'Tofu (čvrsti)',                   search_name:'tofu cvrsti biljni protein',             calories_kcal:110, protein_g:12,   carbs_g:2,   fat_g:4    },
  { id:'sf-seitan',              type:'system', category_id:'cat-mlecni', name_sr:'Seitan',                          search_name:'seitan biljni protein',                  calories_kcal:120, protein_g:21,   carbs_g:2,   fat_g:2    },
  { id:'sf-tempeh',              type:'system', category_id:'cat-mlecni', name_sr:'Tempeh',                          search_name:'tempeh soja biljni protein',             calories_kcal:193, protein_g:19,   carbs_g:11,  fat_g:9    },
  { id:'sf-protein-puding-kokos',type:'system', category_id:'cat-mlecni', name_sr:'Proteinski puding (kokos-badem)',  search_name:'proteinski puding kokos badem',          calories_kcal:87,  protein_g:10,   carbs_g:7,   fat_g:2    },
  { id:'sf-protein-puding-cok',  type:'system', category_id:'cat-mlecni', name_sr:'Proteinski puding (čokolada)',    search_name:'proteinski puding cokolada',             calories_kcal:80,  protein_g:10,   carbs_g:6,   fat_g:1.6  },

  // ── SUPLEMENTI ───────────────────────────────────────────────────────────────
  { id:'sf-whey',                type:'system', category_id:'cat-supp',   name_sr:'Whey protein',                    search_name:'whey protein prah merica',               calories_kcal:120, protein_g:24,   carbs_g:2,   fat_g:1,   serving_g:30, serving_label:'merica' },
  { id:'sf-protein-grasak',      type:'system', category_id:'cat-supp',   name_sr:'Protein iz graška',               search_name:'protein grasak biljni',                  calories_kcal:150, protein_g:25,   carbs_g:1,   fat_g:3    },
  { id:'sf-sojini-proteini',     type:'system', category_id:'cat-supp',   name_sr:'Sojini proteini (izolat)',         search_name:'sojini proteini izolat vegan',           calories_kcal:90,  protein_g:23,   carbs_g:1,   fat_g:0.5  },

  // ── ŽITARICE ─────────────────────────────────────────────────────────────────
  { id:'sf-pirinac-beli',        type:'system', category_id:'cat-zitarice', name_sr:'Pirinač beli',                  search_name:'pirinac beli sirov',                     calories_kcal:365, protein_g:7.1,  carbs_g:80,  fat_g:0.6  },
  { id:'sf-pirinac-int',         type:'system', category_id:'cat-zitarice', name_sr:'Pirinač integralni',            search_name:'pirinac integralni',                     calories_kcal:370, protein_g:7.9,  carbs_g:76,  fat_g:2.7  },
  { id:'sf-ovsene',              type:'system', category_id:'cat-zitarice', name_sr:'Ovsene pahuljice',              search_name:'ovsene pahuljice ovas',                  calories_kcal:379, protein_g:13.2, carbs_g:66.3,fat_g:6.5  },
  { id:'sf-kuskus',              type:'system', category_id:'cat-zitarice', name_sr:'Kus-kus',                       search_name:'kuskus kus kus',                         calories_kcal:376, protein_g:12.8, carbs_g:77.4,fat_g:0.6  },
  { id:'sf-palenta',             type:'system', category_id:'cat-zitarice', name_sr:'Palenta (kukuruzna krupica)',   search_name:'palenta kukuruzna krupica',               calories_kcal:370, protein_g:7.5,  carbs_g:79,  fat_g:1    },
  { id:'sf-bulgur',              type:'system', category_id:'cat-zitarice', name_sr:'Bulgur',                        search_name:'bulgur',                                 calories_kcal:342, protein_g:12.3, carbs_g:76,  fat_g:1.3  },
  { id:'sf-heljda',              type:'system', category_id:'cat-zitarice', name_sr:'Heljda',                        search_name:'heljda',                                 calories_kcal:343, protein_g:13.3, carbs_g:71.5,fat_g:3.4  },
  { id:'sf-kinoa',               type:'system', category_id:'cat-zitarice', name_sr:'Kinoa',                         search_name:'kinoa kvinoja',                          calories_kcal:368, protein_g:14.1, carbs_g:64,  fat_g:6.1  },
  { id:'sf-amarant',             type:'system', category_id:'cat-zitarice', name_sr:'Amarant',                       search_name:'amarant',                                calories_kcal:371, protein_g:13.6, carbs_g:66,  fat_g:7    },
  { id:'sf-griz',                type:'system', category_id:'cat-zitarice', name_sr:'Pšenični / pirinčani griz',     search_name:'griz psenicni pirincani',                calories_kcal:360, protein_g:11,   carbs_g:73,  fat_g:1    },
  { id:'sf-proso',               type:'system', category_id:'cat-zitarice', name_sr:'Proso',                         search_name:'proso',                                  calories_kcal:378, protein_g:11,   carbs_g:73,  fat_g:4.2  },
  { id:'sf-spelta',              type:'system', category_id:'cat-zitarice', name_sr:'Spelta',                        search_name:'spelta',                                 calories_kcal:338, protein_g:14.6, carbs_g:70,  fat_g:2.4  },
  { id:'sf-brasno',              type:'system', category_id:'cat-zitarice', name_sr:'Pšenično brašno T-500',         search_name:'psenicno brasno t500',                   calories_kcal:364, protein_g:10.3, carbs_g:76,  fat_g:1    },
  { id:'sf-cornflakes',          type:'system', category_id:'cat-zitarice', name_sr:'Cornflakes (nezaslađen)',        search_name:'cornflakes nezasladjen',                  calories_kcal:357, protein_g:8,    carbs_g:84,  fat_g:0.4  },
  { id:'sf-granola',             type:'system', category_id:'cat-zitarice', name_sr:'Granola',                       search_name:'granola',                                calories_kcal:489, protein_g:11,   carbs_g:64,  fat_g:20   },
  { id:'sf-musli',               type:'system', category_id:'cat-zitarice', name_sr:'Musli sa suvim voćem',          search_name:'musli suvo voce',                        calories_kcal:450, protein_g:9,    carbs_g:65,  fat_g:15   },
  { id:'sf-pirinc-galete',       type:'system', category_id:'cat-zitarice', name_sr:'Pirinčane galete',              search_name:'pirincane galete rice cake',              calories_kcal:381, protein_g:7.5,  carbs_g:80,  fat_g:3    },

  // ── HLEB & TORTILJE ──────────────────────────────────────────────────────────
  { id:'sf-tost-int',            type:'system', category_id:'cat-hleb', name_sr:'Tost integralni',                   search_name:'tost integralni hleb',                   calories_kcal:247, protein_g:8.9,  carbs_g:41,  fat_g:3.1  },
  { id:'sf-hleb-beli',           type:'system', category_id:'cat-hleb', name_sr:'Beli hleb',                         search_name:'beli hleb',                              calories_kcal:265, protein_g:8.8,  carbs_g:49,  fat_g:3.2  },
  { id:'sf-hleb-int',            type:'system', category_id:'cat-hleb', name_sr:'Integralni hleb',                   search_name:'integralni hleb',                        calories_kcal:247, protein_g:9.3,  carbs_g:41,  fat_g:3    },
  { id:'sf-wasa',                type:'system', category_id:'cat-hleb', name_sr:'WASA hleb',                         search_name:'wasa hleb',                              calories_kcal:360, protein_g:8.7,  carbs_g:61.7,fat_g:1.7  },
  { id:'sf-dvopek',              type:'system', category_id:'cat-hleb', name_sr:'Dvopek',                            search_name:'dvopek prepecenac',                      calories_kcal:400, protein_g:11,   carbs_g:77,  fat_g:2.3  },
  { id:'sf-tortilja-psen',       type:'system', category_id:'cat-hleb', name_sr:'Tortilje (pšenične)',               search_name:'tortilje psenicne',                      calories_kcal:310, protein_g:8,    carbs_g:49,  fat_g:7    },
  { id:'sf-tortilja-kuk',        type:'system', category_id:'cat-hleb', name_sr:'Tortilje (kukuruzne)',              search_name:'tortilje kukuruzne',                     calories_kcal:218, protein_g:5.7,  carbs_g:45,  fat_g:2.9  },
  { id:'sf-tortilja-int',        type:'system', category_id:'cat-hleb', name_sr:'Tortilje (integralne)',             search_name:'tortilje integralne',                    calories_kcal:283, protein_g:9.5,  carbs_g:45,  fat_g:7.2  },
  { id:'sf-testenine-bele',      type:'system', category_id:'cat-hleb', name_sr:'Testenine (bele, suve)',            search_name:'testenine bele suve pasta',              calories_kcal:371, protein_g:12.5, carbs_g:75,  fat_g:1.5  },
  { id:'sf-testenine-int',       type:'system', category_id:'cat-hleb', name_sr:'Testenine (integralne, suve)',      search_name:'testenine integralne suve',              calories_kcal:348, protein_g:12,   carbs_g:68,  fat_g:2    },
  { id:'sf-penne',               type:'system', category_id:'cat-hleb', name_sr:'Penne / Spagete',                  search_name:'penne spagete pasta',                    calories_kcal:360, protein_g:16,   carbs_g:71,  fat_g:3.6  },

  // ── KROMPIR & MAHUNARKE ──────────────────────────────────────────────────────
  { id:'sf-batat',               type:'system', category_id:'cat-krompir', name_sr:'Batat (slatki krompir)',         search_name:'batat slatki krompir',                   calories_kcal:86,  protein_g:1.6,  carbs_g:20,  fat_g:0.1  },
  { id:'sf-krompir',             type:'system', category_id:'cat-krompir', name_sr:'Beli krompir',                  search_name:'beli krompir sirov',                     calories_kcal:77,  protein_g:2,    carbs_g:17,  fat_g:0    },
  { id:'sf-grasak-suvi',         type:'system', category_id:'cat-krompir', name_sr:'Grašak (suvi)',                  search_name:'grasak suvi mahunarke',                  calories_kcal:352, protein_g:25,   carbs_g:61,  fat_g:1.2  },
  { id:'sf-leca',                type:'system', category_id:'cat-krompir', name_sr:'Leća (zelena)',                  search_name:'leca zelena socivo mahunarke',           calories_kcal:352, protein_g:25,   carbs_g:63,  fat_g:1.1  },
  { id:'sf-pasulj',              type:'system', category_id:'cat-krompir', name_sr:'Pasulj (crveni)',                search_name:'pasulj crveni grah mahunarke',           calories_kcal:337, protein_g:23,   carbs_g:61,  fat_g:1.2  },
  { id:'sf-socivo',              type:'system', category_id:'cat-krompir', name_sr:'Sočivo',                         search_name:'socivo leca mahunarke',                  calories_kcal:353, protein_g:26,   carbs_g:60,  fat_g:1.1  },

  // ── VOĆE ─────────────────────────────────────────────────────────────────────
  { id:'sf-banana',              type:'system', category_id:'cat-voce',    name_sr:'Banana',                         search_name:'banana',                                 calories_kcal:89,  protein_g:1.1,  carbs_g:23,  fat_g:0.3  },
  { id:'sf-jabuka',              type:'system', category_id:'cat-voce',    name_sr:'Jabuka',                         search_name:'jabuka',                                 calories_kcal:52,  protein_g:0.3,  carbs_g:14,  fat_g:0.2  },
  { id:'sf-kruska',              type:'system', category_id:'cat-voce',    name_sr:'Kruška',                         search_name:'kruska',                                 calories_kcal:57,  protein_g:0.4,  carbs_g:15,  fat_g:0.1  },
  { id:'sf-grozdje',             type:'system', category_id:'cat-voce',    name_sr:'Grožđe',                         search_name:'grozdje',                                calories_kcal:69,  protein_g:0.7,  carbs_g:18,  fat_g:0.2  },
  { id:'sf-breskva',             type:'system', category_id:'cat-voce',    name_sr:'Breskva',                        search_name:'breskva',                                calories_kcal:39,  protein_g:0.9,  carbs_g:10,  fat_g:0.3  },
  { id:'sf-nektarina',           type:'system', category_id:'cat-voce',    name_sr:'Nektarina',                      search_name:'nektarina',                              calories_kcal:44,  protein_g:1.1,  carbs_g:11,  fat_g:0.3  },
  { id:'sf-pomorandza',          type:'system', category_id:'cat-voce',    name_sr:'Pomorandža',                     search_name:'pomorandza narandza',                    calories_kcal:47,  protein_g:0.9,  carbs_g:12,  fat_g:0.1  },
  { id:'sf-mandarina',           type:'system', category_id:'cat-voce',    name_sr:'Mandarina',                      search_name:'mandarina',                              calories_kcal:53,  protein_g:0.8,  carbs_g:13,  fat_g:0.3  },
  { id:'sf-limun',               type:'system', category_id:'cat-voce',    name_sr:'Limun',                          search_name:'limun',                                  calories_kcal:29,  protein_g:1.1,  carbs_g:9,   fat_g:0.3  },
  { id:'sf-grejpfrut',           type:'system', category_id:'cat-voce',    name_sr:'Grejpfrut',                      search_name:'grejpfrut',                              calories_kcal:42,  protein_g:0.8,  carbs_g:11,  fat_g:0.1  },
  { id:'sf-ananas',              type:'system', category_id:'cat-voce',    name_sr:'Ananas',                         search_name:'ananas',                                 calories_kcal:50,  protein_g:0.5,  carbs_g:13,  fat_g:0.1  },
  { id:'sf-kivi',                type:'system', category_id:'cat-voce',    name_sr:'Kivi',                           search_name:'kivi',                                   calories_kcal:61,  protein_g:1.1,  carbs_g:15,  fat_g:0.5  },
  { id:'sf-jagode',              type:'system', category_id:'cat-voce',    name_sr:'Jagode',                         search_name:'jagode',                                 calories_kcal:32,  protein_g:0.7,  carbs_g:8,   fat_g:0.3  },
  { id:'sf-maline',              type:'system', category_id:'cat-voce',    name_sr:'Maline',                         search_name:'maline malina',                          calories_kcal:52,  protein_g:1.2,  carbs_g:12,  fat_g:0.7  },
  { id:'sf-kupine',              type:'system', category_id:'cat-voce',    name_sr:'Kupine',                         search_name:'kupine',                                 calories_kcal:43,  protein_g:1.4,  carbs_g:10,  fat_g:0.4  },
  { id:'sf-borovnice',           type:'system', category_id:'cat-voce',    name_sr:'Borovnice',                      search_name:'borovnice',                              calories_kcal:57,  protein_g:0.7,  carbs_g:14,  fat_g:0.3  },
  { id:'sf-visnje',              type:'system', category_id:'cat-voce',    name_sr:'Višnje',                         search_name:'visnje',                                 calories_kcal:50,  protein_g:1,    carbs_g:12,  fat_g:0.3  },
  { id:'sf-tresnje',             type:'system', category_id:'cat-voce',    name_sr:'Trešnje',                        search_name:'tresnje',                                calories_kcal:63,  protein_g:1.1,  carbs_g:16,  fat_g:0.2  },
  { id:'sf-lubenica',            type:'system', category_id:'cat-voce',    name_sr:'Lubenica',                       search_name:'lubenica',                               calories_kcal:30,  protein_g:0.6,  carbs_g:8,   fat_g:0.2  },
  { id:'sf-dinja',               type:'system', category_id:'cat-voce',    name_sr:'Dinja',                          search_name:'dinja',                                  calories_kcal:34,  protein_g:0.8,  carbs_g:8,   fat_g:0.2  },
  { id:'sf-smokve-sveze',        type:'system', category_id:'cat-voce',    name_sr:'Smokve (sveže)',                 search_name:'smokve sveze',                           calories_kcal:74,  protein_g:0.8,  carbs_g:19,  fat_g:0.3  },
  { id:'sf-nar',                 type:'system', category_id:'cat-voce',    name_sr:'Nar',                            search_name:'nar',                                    calories_kcal:83,  protein_g:1.7,  carbs_g:19,  fat_g:1.2  },
  { id:'sf-mango',               type:'system', category_id:'cat-voce',    name_sr:'Mango',                          search_name:'mango',                                  calories_kcal:60,  protein_g:0.8,  carbs_g:15,  fat_g:0.4  },
  { id:'sf-smokve-suve',         type:'system', category_id:'cat-voce',    name_sr:'Smokve (suve)',                  search_name:'smokve suve suseno voce',                calories_kcal:249, protein_g:3.3,  carbs_g:64,  fat_g:0.9  },
  { id:'sf-urme',                type:'system', category_id:'cat-voce',    name_sr:'Urme (suve)',                    search_name:'urme suve hurme',                        calories_kcal:282, protein_g:2.5,  carbs_g:75,  fat_g:0.4  },
  { id:'sf-suve-sljive',         type:'system', category_id:'cat-voce',    name_sr:'Suve šljive',                   search_name:'suve sljive',                            calories_kcal:240, protein_g:2.2,  carbs_g:64,  fat_g:0.4  },
  { id:'sf-grozdje-belo',       type:'system', category_id:'cat-voce',    name_sr:'Grožđe (belo)',                 search_name:'grozdje belo',                           calories_kcal:67,  protein_g:0.6,  carbs_g:17,  fat_g:0.2  },
  { id:'sf-grozdje-crno',       type:'system', category_id:'cat-voce',    name_sr:'Grožđe (crno)',                 search_name:'grozdje crno',                           calories_kcal:69,  protein_g:0.7,  carbs_g:18,  fat_g:0.2  },
  { id:'sf-lubenica-2',         type:'system', category_id:'cat-voce',    name_sr:'Lubenica (bez kore)',           search_name:'lubenica bez kore voce leto',            calories_kcal:30,  protein_g:0.6,  carbs_g:7.6, fat_g:0.2  },
  { id:'sf-papaja',             type:'system', category_id:'cat-voce',    name_sr:'Papaja',                        search_name:'papaja',                                 calories_kcal:43,  protein_g:0.5,  carbs_g:11,  fat_g:0.3  },
  { id:'sf-marakuja',           type:'system', category_id:'cat-voce',    name_sr:'Marakuja',                      search_name:'marakuja passion fruit',                 calories_kcal:97,  protein_g:2.2,  carbs_g:23,  fat_g:0.7  },
  { id:'sf-kokos-svez',         type:'system', category_id:'cat-voce',    name_sr:'Kokos (svež, meso)',            search_name:'kokos svez meso',                        calories_kcal:354, protein_g:3.3,  carbs_g:15,  fat_g:33   },
  { id:'sf-liči',               type:'system', category_id:'cat-voce',    name_sr:'Liči',                          search_name:'lici',                                   calories_kcal:66,  protein_g:0.8,  carbs_g:17,  fat_g:0.4  },
  { id:'sf-guava',              type:'system', category_id:'cat-voce',    name_sr:'Guava',                         search_name:'guava',                                  calories_kcal:68,  protein_g:2.6,  carbs_g:14,  fat_g:1    },
  { id:'sf-sljiva',              type:'system', category_id:'cat-voce',    name_sr:'Šljiva (sveža)',                 search_name:'sljiva sveza',                           calories_kcal:46,  protein_g:0.7,  carbs_g:11,  fat_g:0.3  },
  { id:'sf-kajsija',             type:'system', category_id:'cat-voce',    name_sr:'Kajsija',                        search_name:'kajsija abrikosa',                       calories_kcal:48,  protein_g:1.4,  carbs_g:11,  fat_g:0.4  },
  { id:'sf-trnjina',             type:'system', category_id:'cat-voce',    name_sr:'Drenjina / Trnjina',             search_name:'drenjina trnjina divlje voce',           calories_kcal:60,  protein_g:0.6,  carbs_g:14,  fat_g:0.2  },
  { id:'sf-dud',                 type:'system', category_id:'cat-voce',    name_sr:'Dud (beli/crni)',                search_name:'dud beli crni',                          calories_kcal:43,  protein_g:1.4,  carbs_g:9.8, fat_g:0.4  },
  { id:'sf-glog',                type:'system', category_id:'cat-voce',    name_sr:'Glog',                           search_name:'glog divlje voce',                       calories_kcal:52,  protein_g:0.8,  carbs_g:12,  fat_g:0.5  },
  { id:'sf-ribizla',             type:'system', category_id:'cat-voce',    name_sr:'Ribizla (crna/crvena)',          search_name:'ribizla crna crvena',                    calories_kcal:56,  protein_g:1.4,  carbs_g:13,  fat_g:0.2  },
  { id:'sf-ogrozd',              type:'system', category_id:'cat-voce',    name_sr:'Ogrozd',                         search_name:'ogrozd',                                 calories_kcal:44,  protein_g:0.9,  carbs_g:10,  fat_g:0.6  },
  { id:'sf-kaki',                type:'system', category_id:'cat-voce',    name_sr:'Kaki (hurma)',                   search_name:'kaki hurma voce',                        calories_kcal:70,  protein_g:0.6,  carbs_g:19,  fat_g:0.2  },
  { id:'sf-sljiva-suva',         type:'system', category_id:'cat-voce',    name_sr:'Kajsija (suva)',                 search_name:'kajsija suva osusena',                   calories_kcal:241, protein_g:3.4,  carbs_g:63,  fat_g:0.5  },

  // ── POVRĆE ───────────────────────────────────────────────────────────────────
  { id:'sf-sargarepa',           type:'system', category_id:'cat-povrce',  name_sr:'Šargarepa',                      search_name:'sargarepa mrkva',                        calories_kcal:41,  protein_g:0.9,  carbs_g:10,  fat_g:0.2  },
  { id:'sf-tikvica',             type:'system', category_id:'cat-povrce',  name_sr:'Tikvica',                        search_name:'tikvica',                                calories_kcal:17,  protein_g:1.2,  carbs_g:3.1, fat_g:0.3  },
  { id:'sf-krastavac',           type:'system', category_id:'cat-povrce',  name_sr:'Krastavac',                      search_name:'krastavac',                              calories_kcal:15,  protein_g:0.6,  carbs_g:3.6, fat_g:0.1  },
  { id:'sf-paradajz',            type:'system', category_id:'cat-povrce',  name_sr:'Paradajz',                       search_name:'paradajz',                               calories_kcal:18,  protein_g:0.9,  carbs_g:3.9, fat_g:0.2  },
  { id:'sf-paprika-crvena',      type:'system', category_id:'cat-povrce',  name_sr:'Paprika (crvena)',               search_name:'paprika crvena',                         calories_kcal:31,  protein_g:1,    carbs_g:6,   fat_g:0.3  },
  { id:'sf-paprika-zelena',      type:'system', category_id:'cat-povrce',  name_sr:'Paprika (zelena)',               search_name:'paprika zelena',                         calories_kcal:20,  protein_g:0.9,  carbs_g:4.6, fat_g:0.2  },
  { id:'sf-luk-crni',            type:'system', category_id:'cat-povrce',  name_sr:'Crni luk',                       search_name:'crni luk',                               calories_kcal:40,  protein_g:1.1,  carbs_g:9.3, fat_g:0.1  },
  { id:'sf-luk-mladi',           type:'system', category_id:'cat-povrce',  name_sr:'Luk beli (mladi)',               search_name:'luk beli mladi',                         calories_kcal:32,  protein_g:1.2,  carbs_g:7.3, fat_g:0.2  },
  { id:'sf-brokoli',             type:'system', category_id:'cat-povrce',  name_sr:'Brokoli',                        search_name:'brokoli',                                calories_kcal:34,  protein_g:2.8,  carbs_g:6.6, fat_g:0.4  },
  { id:'sf-karfiol',             type:'system', category_id:'cat-povrce',  name_sr:'Karfiol',                        search_name:'karfiol',                                calories_kcal:25,  protein_g:2,    carbs_g:5,   fat_g:0.3  },
  { id:'sf-zelena-salata',       type:'system', category_id:'cat-povrce',  name_sr:'Zelena salata',                  search_name:'zelena salata iceberg mix',              calories_kcal:14,  protein_g:1.4,  carbs_g:2.9, fat_g:0.2  },
  { id:'sf-rukola',              type:'system', category_id:'cat-povrce',  name_sr:'Rukola',                         search_name:'rukola',                                 calories_kcal:25,  protein_g:2.6,  carbs_g:3.7, fat_g:0.7  },
  { id:'sf-spanac',              type:'system', category_id:'cat-povrce',  name_sr:'Spanać',                         search_name:'spanac spinat',                          calories_kcal:23,  protein_g:2.9,  carbs_g:3.6, fat_g:0.3  },
  { id:'sf-blitva',              type:'system', category_id:'cat-povrce',  name_sr:'Blitva',                         search_name:'blitva',                                 calories_kcal:19,  protein_g:1.8,  carbs_g:3.7, fat_g:0.2  },
  { id:'sf-cvekla',              type:'system', category_id:'cat-povrce',  name_sr:'Cvekla',                         search_name:'cvekla',                                 calories_kcal:43,  protein_g:1.6,  carbs_g:10,  fat_g:0.2  },
  { id:'sf-kelj',                type:'system', category_id:'cat-povrce',  name_sr:'Kelj',                           search_name:'kelj',                                   calories_kcal:35,  protein_g:2.9,  carbs_g:6,   fat_g:0.4  },
  { id:'sf-bundeva',             type:'system', category_id:'cat-povrce',  name_sr:'Tikva (bundeva)',                search_name:'tikva bundeva',                          calories_kcal:26,  protein_g:1,    carbs_g:6.5, fat_g:0.1  },
  { id:'sf-sampinjoni',          type:'system', category_id:'cat-povrce',  name_sr:'Šampinjoni',                     search_name:'sampinjoni pecurke',                     calories_kcal:22,  protein_g:3.1,  carbs_g:3.3, fat_g:0.3  },
  { id:'sf-patlidzan',           type:'system', category_id:'cat-povrce',  name_sr:'Patlidžan',                      search_name:'patlidzan',                              calories_kcal:25,  protein_g:1,    carbs_g:5.9, fat_g:0.2  },
  { id:'sf-praziluk',            type:'system', category_id:'cat-povrce',  name_sr:'Praziluk',                       search_name:'praziluk por luk',                       calories_kcal:61,  protein_g:1.5,  carbs_g:14,  fat_g:0.3  },
  { id:'sf-celer-koren',         type:'system', category_id:'cat-povrce',  name_sr:'Celer (koren)',                  search_name:'celer koren',                            calories_kcal:42,  protein_g:1.5,  carbs_g:9.2, fat_g:0.3  },
  { id:'sf-celer-list',          type:'system', category_id:'cat-povrce',  name_sr:'Celer (list)',                   search_name:'celer list',                             calories_kcal:14,  protein_g:0.7,  carbs_g:3,   fat_g:0.2  },
  { id:'sf-persun',              type:'system', category_id:'cat-povrce',  name_sr:'Peršun',                         search_name:'persun',                                 calories_kcal:36,  protein_g:3,    carbs_g:6.3, fat_g:0.8  },
  { id:'sf-rotkvica',            type:'system', category_id:'cat-povrce',  name_sr:'Rotkvica',                       search_name:'rotkvica rotkva',                        calories_kcal:16,  protein_g:0.7,  carbs_g:3.4, fat_g:0.1  },
  { id:'sf-repa',                type:'system', category_id:'cat-povrce',  name_sr:'Repa (bela)',                    search_name:'repa bela',                              calories_kcal:28,  protein_g:0.9,  carbs_g:6.4, fat_g:0.1  },
  { id:'sf-beli-luk',            type:'system', category_id:'cat-povrce',  name_sr:'Beli luk',                       search_name:'beli luk cesan',                         calories_kcal:149, protein_g:6.4,  carbs_g:33,  fat_g:0.5  },
  { id:'sf-boranija',            type:'system', category_id:'cat-povrce',  name_sr:'Boranija (zeleni pasulj)',       search_name:'boranija zeleni pasulj mahune',          calories_kcal:31,  protein_g:1.8,  carbs_g:7,   fat_g:0.1  },
  { id:'sf-grasak-svez',         type:'system', category_id:'cat-povrce',  name_sr:'Grašak (svež)',                  search_name:'grasak svez',                            calories_kcal:81,  protein_g:5.4,  carbs_g:14,  fat_g:0.4  },
  { id:'sf-kukuruz-svez',        type:'system', category_id:'cat-povrce',  name_sr:'Kukuruz (svež)',                 search_name:'kukuruz svez zrno klip',                 calories_kcal:86,  protein_g:3.2,  carbs_g:19,  fat_g:1.2  },
  { id:'sf-paprika-zuta',        type:'system', category_id:'cat-povrce',  name_sr:'Paprika (žuta)',                 search_name:'paprika zuta',                           calories_kcal:27,  protein_g:1,    carbs_g:6.3, fat_g:0.2  },
  { id:'sf-kupus',               type:'system', category_id:'cat-povrce',  name_sr:'Kupus (beli)',                   search_name:'kupus beli sirov',                       calories_kcal:25,  protein_g:1.3,  carbs_g:5.8, fat_g:0.1  },
  { id:'sf-kiseli-kupus',        type:'system', category_id:'cat-povrce',  name_sr:'Kiseli kupus',                   search_name:'kiseli kupus',                           calories_kcal:19,  protein_g:0.9,  carbs_g:4.3, fat_g:0.1  },
  { id:'sf-crveni-kupus',        type:'system', category_id:'cat-povrce',  name_sr:'Crveni kupus',                   search_name:'crveni kupus',                           calories_kcal:31,  protein_g:1.4,  carbs_g:7.4, fat_g:0.2  },
  { id:'sf-korabu',              type:'system', category_id:'cat-povrce',  name_sr:'Korabica',                       search_name:'korabica koraba',                        calories_kcal:27,  protein_g:1.7,  carbs_g:6.2, fat_g:0.1  },
  { id:'sf-bamija',              type:'system', category_id:'cat-povrce',  name_sr:'Bamija',                         search_name:'bamija',                                 calories_kcal:33,  protein_g:1.9,  carbs_g:7.5, fat_g:0.2  },
  { id:'sf-masline',             type:'system', category_id:'cat-povrce',  name_sr:'Masline',                        search_name:'masline zelene crne',                    calories_kcal:145, protein_g:1,    carbs_g:3.8, fat_g:15   },
  { id:'sf-spargla',            type:'system', category_id:'cat-povrce',  name_sr:'Špargle',                        search_name:'spargla spargle',                        calories_kcal:20,  protein_g:2.2,  carbs_g:3.9, fat_g:0.1  },
  { id:'sf-artičoka',           type:'system', category_id:'cat-povrce',  name_sr:'Artičoka',                       search_name:'articoka',                               calories_kcal:47,  protein_g:3.3,  carbs_g:10,  fat_g:0.2  },
  { id:'sf-fenjas',             type:'system', category_id:'cat-povrce',  name_sr:'Fenkl (kopar koren)',            search_name:'fenkas kopar koren',                     calories_kcal:31,  protein_g:1.2,  carbs_g:7.3, fat_g:0.2  },
  { id:'sf-pastinak',           type:'system', category_id:'cat-povrce',  name_sr:'Paštrnak',                       search_name:'pastrnak pasnip',                        calories_kcal:75,  protein_g:1.2,  carbs_g:18,  fat_g:0.3  },
  { id:'sf-celer-stabljika',    type:'system', category_id:'cat-povrce',  name_sr:'Celer (stabljika)',              search_name:'celer stabljika',                        calories_kcal:16,  protein_g:0.7,  carbs_g:3,   fat_g:0.2  },
  { id:'sf-endivia',            type:'system', category_id:'cat-povrce',  name_sr:'Endivija / Radič',               search_name:'endivija radic',                         calories_kcal:17,  protein_g:1.3,  carbs_g:3.4, fat_g:0.2  },
  { id:'sf-portulak',           type:'system', category_id:'cat-povrce',  name_sr:'Portulak',                       search_name:'portulak',                               calories_kcal:20,  protein_g:2,    carbs_g:3.4, fat_g:0.4  },
  { id:'sf-cicoka',             type:'system', category_id:'cat-povrce',  name_sr:'Čičoka (topinambur)',            search_name:'cicoka topinambur',                      calories_kcal:73,  protein_g:2,    carbs_g:17,  fat_g:0.1  },
  { id:'sf-rotkva',             type:'system', category_id:'cat-povrce',  name_sr:'Rotkva (crna/bela)',             search_name:'rotkva crna bela',                       calories_kcal:18,  protein_g:0.7,  carbs_g:4.1, fat_g:0.1  },
  { id:'sf-kineski-kupus',      type:'system', category_id:'cat-povrce',  name_sr:'Kineski kupus',                  search_name:'kineski kupus',                          calories_kcal:13,  protein_g:1.5,  carbs_g:2.2, fat_g:0.2  },
  { id:'sf-prokelj',            type:'system', category_id:'cat-povrce',  name_sr:'Prokelj (Brisel klice)',         search_name:'prokelj brisel klice',                   calories_kcal:43,  protein_g:3.4,  carbs_g:9,   fat_g:0.3  },
  { id:'sf-kopar',              type:'system', category_id:'cat-povrce',  name_sr:'Kopar (svež)',                   search_name:'kopar svez mirođija',                    calories_kcal:43,  protein_g:3.5,  carbs_g:7,   fat_g:1.1  },
  { id:'sf-bosiljak',           type:'system', category_id:'cat-povrce',  name_sr:'Bosiljak (svež)',                search_name:'bosiljak svez',                          calories_kcal:23,  protein_g:3.2,  carbs_g:2.7, fat_g:0.6  },
  { id:'sf-mentana',            type:'system', category_id:'cat-povrce',  name_sr:'Nana / Menta (sveža)',           search_name:'nana menta sveza',                       calories_kcal:70,  protein_g:3.8,  carbs_g:15,  fat_g:0.9  },
  { id:'sf-cheri-paradajz',     type:'system', category_id:'cat-povrce',  name_sr:'Čeri paradajz',                  search_name:'ceri paradajz cherry',                   calories_kcal:18,  protein_g:0.9,  carbs_g:3.9, fat_g:0.2  },
  { id:'sf-susen-paradajz',     type:'system', category_id:'cat-povrce',  name_sr:'Sušeni paradajz',               search_name:'suseni paradajz',                        calories_kcal:258, protein_g:14,   carbs_g:56,  fat_g:3    },
  { id:'sf-avokado-zreo',       type:'system', category_id:'cat-povrce',  name_sr:'Avokado (zreo)',                 search_name:'avokado zreo',                           calories_kcal:160, protein_g:2,    carbs_g:9,   fat_g:15   },
  { id:'sf-jalapeno',           type:'system', category_id:'cat-povrce',  name_sr:'Jalapeño (svež)',                search_name:'jalapeno ljuta paprika',                 calories_kcal:29,  protein_g:0.9,  carbs_g:6.5, fat_g:0.4  },

  // ── ULJA ─────────────────────────────────────────────────────────────────────
  { id:'sf-maslinovo',           type:'system', category_id:'cat-ulja',    name_sr:'Maslinovo ulje',                 search_name:'maslinovo ulje',                         calories_kcal:884, protein_g:0,    carbs_g:0,   fat_g:100  },
  { id:'sf-suncokretovo-ulje',   type:'system', category_id:'cat-ulja',    name_sr:'Suncokretovo ulje',              search_name:'suncokretovo ulje',                      calories_kcal:884, protein_g:0,    carbs_g:0,   fat_g:100  },
  { id:'sf-kokosovo-ulje',       type:'system', category_id:'cat-ulja',    name_sr:'Kokosovo ulje',                  search_name:'kokosovo ulje',                          calories_kcal:862, protein_g:0,    carbs_g:0,   fat_g:100  },
  { id:'sf-puter',               type:'system', category_id:'cat-ulja',    name_sr:'Puter (maslac)',                 search_name:'puter maslac',                           calories_kcal:717, protein_g:0.9,  carbs_g:0.1, fat_g:81   },
  { id:'sf-ghee',                type:'system', category_id:'cat-ulja',    name_sr:'Ghee (prečišćeni puter)',        search_name:'ghee precisceni puter',                  calories_kcal:900, protein_g:0,    carbs_g:0,   fat_g:100  },

  // ── ORAŠASTI PLODOVI ─────────────────────────────────────────────────────────
  { id:'sf-orah',                type:'system', category_id:'cat-orasasti', name_sr:'Orah',                          search_name:'orah',                                   calories_kcal:654, protein_g:15,   carbs_g:14,  fat_g:65   },
  { id:'sf-badem',               type:'system', category_id:'cat-orasasti', name_sr:'Badem',                         search_name:'badem',                                  calories_kcal:579, protein_g:21,   carbs_g:22,  fat_g:50   },
  { id:'sf-lesnik',              type:'system', category_id:'cat-orasasti', name_sr:'Lešnik',                        search_name:'lesnik lesnici',                         calories_kcal:628, protein_g:15,   carbs_g:17,  fat_g:61   },
  { id:'sf-kikiriki',            type:'system', category_id:'cat-orasasti', name_sr:'Kikiriki',                      search_name:'kikiriki',                               calories_kcal:567, protein_g:25,   carbs_g:16,  fat_g:49   },
  { id:'sf-kikiriki-puter',      type:'system', category_id:'cat-orasasti', name_sr:'Kikiriki puter (natural)',      search_name:'kikiriki puter natural',                 calories_kcal:588, protein_g:25,   carbs_g:20,  fat_g:50   },
  { id:'sf-pistaci',             type:'system', category_id:'cat-orasasti', name_sr:'Pistaći',                       search_name:'pistaci',                                calories_kcal:562, protein_g:20,   carbs_g:28,  fat_g:45   },
  { id:'sf-indijski-orah',       type:'system', category_id:'cat-orasasti', name_sr:'Indijski orah',                 search_name:'indijski orah kasju',                    calories_kcal:553, protein_g:18,   carbs_g:30,  fat_g:44   },

  // ── SEMENKE ──────────────────────────────────────────────────────────────────
  { id:'sf-chia',                type:'system', category_id:'cat-semenke',  name_sr:'Chia seme',                     search_name:'chia seme semenke',                      calories_kcal:486, protein_g:17,   carbs_g:42,  fat_g:31   },
  { id:'sf-laneno',              type:'system', category_id:'cat-semenke',  name_sr:'Laneno seme',                   search_name:'laneno seme lan',                        calories_kcal:534, protein_g:18,   carbs_g:29,  fat_g:42   },
  { id:'sf-susam',               type:'system', category_id:'cat-semenke',  name_sr:'Susam',                         search_name:'susam',                                  calories_kcal:573, protein_g:17,   carbs_g:23,  fat_g:50   },
  { id:'sf-suncokret-seme',      type:'system', category_id:'cat-semenke',  name_sr:'Semenke suncokreta',            search_name:'semenke suncokreta',                     calories_kcal:584, protein_g:21,   carbs_g:20,  fat_g:52   },

  // ── OSTALO ───────────────────────────────────────────────────────────────────
  { id:'sf-avokado',             type:'system', category_id:'cat-ostalo',   name_sr:'Avokado',                       search_name:'avokado',                                calories_kcal:160, protein_g:2,    carbs_g:9,   fat_g:15   },
  { id:'sf-med',                 type:'system', category_id:'cat-ostalo',   name_sr:'Med',                           search_name:'med',                                    calories_kcal:304, protein_g:0.3,  carbs_g:82,  fat_g:0    },
  { id:'sf-plazma',              type:'system', category_id:'cat-ostalo',   name_sr:'Plazma',                        search_name:'plazma keks',                            calories_kcal:440, protein_g:11,   carbs_g:68,  fat_g:12   },
  { id:'sf-light-pavlaka',       type:'system', category_id:'cat-ostalo',   name_sr:'Light pavlaka za kuvanje',      search_name:'light pavlaka kuvanje',                  calories_kcal:120, protein_g:3,    carbs_g:6,   fat_g:10   },
  { id:'sf-pavlaka-20',          type:'system', category_id:'cat-ostalo',   name_sr:'Pavlaka (20% m.m.)',            search_name:'pavlaka 20 posto',                       calories_kcal:206, protein_g:2.9,  carbs_g:3.2, fat_g:20   },
  { id:'sf-kisela-pavlaka',      type:'system', category_id:'cat-ostalo',   name_sr:'Kisela pavlaka (12% m.m.)',     search_name:'kisela pavlaka 12 posto',                calories_kcal:143, protein_g:3.3,  carbs_g:4.1, fat_g:12   },
  { id:'sf-pasirani-paradajz',   type:'system', category_id:'cat-ostalo',   name_sr:'Pasirani paradajz',             search_name:'pasirani paradajz passata',              calories_kcal:30,  protein_g:1,    carbs_g:6,   fat_g:0    },
  { id:'sf-ajvar',               type:'system', category_id:'cat-ostalo',   name_sr:'Ajvar',                         search_name:'ajvar blagi ljuti',                      calories_kcal:90,  protein_g:1.4,  carbs_g:7.5, fat_g:6    },
  { id:'sf-majonez',             type:'system', category_id:'cat-ostalo',   name_sr:'Majonez',                       search_name:'majonez',                                calories_kcal:680, protein_g:1,    carbs_g:1,   fat_g:75   },
  { id:'sf-senf',                type:'system', category_id:'cat-ostalo',   name_sr:'Senf',                          search_name:'senf mustard',                           calories_kcal:66,  protein_g:4.4,  carbs_g:6.7, fat_g:3.7  },
  { id:'sf-kecap',               type:'system', category_id:'cat-ostalo',   name_sr:'Kečap',                         search_name:'kecap',                                  calories_kcal:112, protein_g:1.3,  carbs_g:26,  fat_g:0.2  },
  { id:'sf-bbq-sos',             type:'system', category_id:'cat-ostalo',   name_sr:'BBQ sos',                       search_name:'bbq sos',                                calories_kcal:150, protein_g:1,    carbs_g:35,  fat_g:0.5  },
  { id:'sf-humus',               type:'system', category_id:'cat-ostalo',   name_sr:'Humus',                         search_name:'humus slanutak',                         calories_kcal:237, protein_g:8,    carbs_g:14,  fat_g:17   },
  { id:'sf-tahini',              type:'system', category_id:'cat-ostalo',   name_sr:'Tahini (pasta od susama)',       search_name:'tahini pasta susam',                     calories_kcal:595, protein_g:17,   carbs_g:22,  fat_g:54   },
  { id:'sf-kajmak',             type:'system', category_id:'cat-ostalo',   name_sr:'Kajmak',                         search_name:'kajmak',                                 calories_kcal:320, protein_g:3,    carbs_g:2,   fat_g:33   },
  { id:'sf-urnebes',            type:'system', category_id:'cat-ostalo',   name_sr:'Urnebes',                        search_name:'urnebes',                                calories_kcal:280, protein_g:12,   carbs_g:3,   fat_g:25   },
  { id:'sf-kiselo-mleko',       type:'system', category_id:'cat-mlecni',   name_sr:'Kiselo mleko',                   search_name:'kiselo mleko jogurt',                    calories_kcal:61,  protein_g:3.3,  carbs_g:4.7, fat_g:3.3  },
  { id:'sf-kefir',              type:'system', category_id:'cat-mlecni',   name_sr:'Kefir',                          search_name:'kefir',                                  calories_kcal:52,  protein_g:3.4,  carbs_g:4.8, fat_g:1    },
  { id:'sf-surutka',            type:'system', category_id:'cat-mlecni',   name_sr:'Surutka',                        search_name:'surutka',                                calories_kcal:24,  protein_g:0.8,  carbs_g:5.1, fat_g:0.4  },
  { id:'sf-prebranac-sir',      type:'system', category_id:'cat-mlecni',   name_sr:'Beli sir u salamuri',            search_name:'beli sir salamura feta domaci',          calories_kcal:230, protein_g:14,   carbs_g:2,   fat_g:18   },
  { id:'sf-sudžuk',             type:'system', category_id:'cat-meso',     name_sr:'Sudžuk',                         search_name:'sudzuk',                                 calories_kcal:420, protein_g:18,   carbs_g:1,   fat_g:38   },
  { id:'sf-crni-luk-svez',      type:'system', category_id:'cat-povrce',   name_sr:'Mladi crni luk (kapula)',        search_name:'mladi crni luk kapula',                  calories_kcal:32,  protein_g:1.1,  carbs_g:7.3, fat_g:0.2  },
  { id:'sf-papar',              type:'system', category_id:'cat-ostalo',   name_sr:'Ljuta paprika (sirov)',          search_name:'ljuta paprika sveza',                    calories_kcal:40,  protein_g:1.9,  carbs_g:8.8, fat_g:0.4  },
  { id:'sf-ren',                type:'system', category_id:'cat-ostalo',   name_sr:'Ren (hren)',                     search_name:'ren hren',                               calories_kcal:48,  protein_g:1.2,  carbs_g:11,  fat_g:0.7  },
  { id:'sf-jaje-prepelice',    type:'system', category_id:'cat-jaja',     name_sr:'Jaje prepelice',                 search_name:'jaje prepelice',                         calories_kcal:158, protein_g:13,   carbs_g:0.4, fat_g:11,   serving_g:10, serving_label:'kom' },
  { id:'sf-jaje-patke',        type:'system', category_id:'cat-jaja',     name_sr:'Pačije jaje',                   search_name:'packo jaje patka',                       calories_kcal:185, protein_g:13,   carbs_g:1.4, fat_g:14,   serving_g:70, serving_label:'kom' },
  { id:'sf-leblebija',         type:'system', category_id:'cat-krompir',  name_sr:'Leblebija (slanutak)',           search_name:'leblebija slanutak',                     calories_kcal:364, protein_g:19,   carbs_g:61,  fat_g:6    },
  { id:'sf-bob',               type:'system', category_id:'cat-krompir',  name_sr:'Bob (sirovi)',                   search_name:'bob fava beans',                         calories_kcal:341, protein_g:26,   carbs_g:58,  fat_g:1.5  },
  { id:'sf-mungo',             type:'system', category_id:'cat-krompir',  name_sr:'Mungo pasulj',                  search_name:'mungo pasulj beans',                     calories_kcal:347, protein_g:24,   carbs_g:63,  fat_g:1.1  },
  { id:'sf-kukuruz-suve',      type:'system', category_id:'cat-krompir',  name_sr:'Kukuruz (suve zrno)',            search_name:'kukuruz suve zrno popcorn',              calories_kcal:365, protein_g:9,    carbs_g:74,  fat_g:4.7  },
  { id:'sf-batate-kuvane',     type:'system', category_id:'cat-krompir',  name_sr:'Batat (kuvani)',                 search_name:'batat kuvani',                           calories_kcal:76,  protein_g:1.4,  carbs_g:18,  fat_g:0.1  },
  { id:'sf-kokice',            type:'system', category_id:'cat-zitarice', name_sr:'Kokice (bez maslaca)',           search_name:'kokice popcorn',                         calories_kcal:387, protein_g:13,   carbs_g:78,  fat_g:4.5  },
  { id:'sf-divlji-pirinac',    type:'system', category_id:'cat-zitarice', name_sr:'Divlji pirinač',                search_name:'divlji pirinac wild rice',               calories_kcal:357, protein_g:14,   carbs_g:75,  fat_g:1.1  },
  { id:'sf-jecam',             type:'system', category_id:'cat-zitarice', name_sr:'Ječam (zrno)',                  search_name:'jecam zrno',                             calories_kcal:354, protein_g:12,   carbs_g:73,  fat_g:2.3  },
  { id:'sf-raz',               type:'system', category_id:'cat-zitarice', name_sr:'Raž (zrno)',                    search_name:'raz zrno',                               calories_kcal:338, protein_g:10,   carbs_g:76,  fat_g:1.6  },
  { id:'sf-prebioticke',       type:'system', category_id:'cat-zitarice', name_sr:'Zobene mekinje',                search_name:'zobene mekinje ovsene',                  calories_kcal:246, protein_g:17,   carbs_g:66,  fat_g:7    },
  { id:'sf-psenicne-mekinje',  type:'system', category_id:'cat-zitarice', name_sr:'Pšenične mekinje',              search_name:'psenicne mekinje',                       calories_kcal:216, protein_g:16,   carbs_g:65,  fat_g:4.3  },
  { id:'sf-badem-brasno',      type:'system', category_id:'cat-orasasti', name_sr:'Bademovo brašno',               search_name:'bademovo brasno',                        calories_kcal:571, protein_g:21,   carbs_g:21,  fat_g:50   },
  { id:'sf-kokos-brasno',      type:'system', category_id:'cat-ostalo',   name_sr:'Kokosovo brašno',               search_name:'kokosovo brasno',                        calories_kcal:400, protein_g:19,   carbs_g:60,  fat_g:15   },
  { id:'sf-protein-bar',       type:'system', category_id:'cat-supp',     name_sr:'Proteinska pločica (prosek)',   search_name:'proteinska plocica bar',                 calories_kcal:350, protein_g:25,   carbs_g:40,  fat_g:10   },
  { id:'sf-creatine',          type:'system', category_id:'cat-supp',     name_sr:'Kreatin (monohidrat)',           search_name:'kreatin creatine',                       calories_kcal:0,   protein_g:0,    carbs_g:0,   fat_g:0    },
  { id:'sf-bcaa',              type:'system', category_id:'cat-supp',     name_sr:'BCAA',                           search_name:'bcaa aminokiseline',                     calories_kcal:40,  protein_g:10,   carbs_g:0,   fat_g:0    },
  { id:'sf-kakao-prah',        type:'system', category_id:'cat-ostalo',   name_sr:'Kakao prah (nesladjen)',         search_name:'kakao prah nesladjen',                   calories_kcal:228, protein_g:20,   carbs_g:58,  fat_g:14   },
  { id:'sf-crna-cok',          type:'system', category_id:'cat-ostalo',   name_sr:'Crna čokolada (70%+)',           search_name:'crna cokolada tamna',                    calories_kcal:598, protein_g:8,    carbs_g:46,  fat_g:43   },
  { id:'sf-dzem',              type:'system', category_id:'cat-ostalo',   name_sr:'Džem (voćni)',                   search_name:'dzem vocni',                             calories_kcal:250, protein_g:0.5,  carbs_g:65,  fat_g:0.1  },
  { id:'sf-nutela',            type:'system', category_id:'cat-ostalo',   name_sr:'Nutella / čoko krem',            search_name:'nutella coko krem',                      calories_kcal:539, protein_g:6,    carbs_g:57,  fat_g:31   },
  { id:'sf-sirup-javorov',     type:'system', category_id:'cat-ostalo',   name_sr:'Javorov sirup',                 search_name:'javorov sirup',                          calories_kcal:260, protein_g:0,    carbs_g:67,  fat_g:0.1  },
  { id:'sf-agave',             type:'system', category_id:'cat-ostalo',   name_sr:'Agavin sirup',                  search_name:'agave sirup',                            calories_kcal:310, protein_g:0.1,  carbs_g:78,  fat_g:0.2  },
  { id:'sf-stevia',            type:'system', category_id:'cat-ostalo',   name_sr:'Stevija',                        search_name:'stevija zaslađivac',                     calories_kcal:0,   protein_g:0,    carbs_g:0,   fat_g:0    },
  { id:'sf-kefir-mast',        type:'system', category_id:'cat-mlecni',   name_sr:'Kefir (3.2% m.m.)',             search_name:'kefir mastan',                           calories_kcal:61,  protein_g:3.4,  carbs_g:4.7, fat_g:3.4  },
  { id:'sf-jogurt-punomasni',  type:'system', category_id:'cat-mlecni',   name_sr:'Jogurt (punomasni, 3.2%)',      search_name:'jogurt punomasni',                       calories_kcal:61,  protein_g:3.5,  carbs_g:4.7, fat_g:3.3  },
  { id:'sf-jogurt-0',          type:'system', category_id:'cat-mlecni',   name_sr:'Jogurt (0% m.m.)',              search_name:'jogurt nemasni 0 posto',                 calories_kcal:35,  protein_g:3.8,  carbs_g:5,   fat_g:0.1  },
  { id:'sf-mleko-punomasno',   type:'system', category_id:'cat-mlecni',   name_sr:'Mleko (3.2% m.m.)',             search_name:'mleko punomasno 32',                     calories_kcal:65,  protein_g:3.2,  carbs_g:4.8, fat_g:3.6  },
  { id:'sf-mleko-bez-laktoze', type:'system', category_id:'cat-mlecni',   name_sr:'Mleko bez laktoze',             search_name:'mleko bez laktoze',                      calories_kcal:46,  protein_g:3.4,  carbs_g:5,   fat_g:1.5  },
  { id:'sf-bademovo-mleko',    type:'system', category_id:'cat-mlecni',   name_sr:'Bademovo mleko (nesladeno)',     search_name:'bademovo mleko',                         calories_kcal:20,  protein_g:0.4,  carbs_g:0.8, fat_g:1.5  },
  { id:'sf-ovseno-mleko',      type:'system', category_id:'cat-mlecni',   name_sr:'Ovseno mleko',                  search_name:'ovseno mleko',                           calories_kcal:45,  protein_g:1,    carbs_g:6.5, fat_g:1.5  },
  { id:'sf-sojino-mleko',      type:'system', category_id:'cat-mlecni',   name_sr:'Sojino mleko',                  search_name:'sojino mleko',                           calories_kcal:33,  protein_g:3.3,  carbs_g:2.9, fat_g:1.8  },
]

export function searchFoods(query: string, userFoods: FoodItem[] = []): FoodItem[] {
  if (!query.trim()) return []
  const q = query.toLowerCase()
    .replace(/[čć]/g, 'c').replace(/š/g, 's').replace(/ž/g, 'z').replace(/đ/g, 'dj')
  const all = [...userFoods, ...SYSTEM_FOODS]
  return all.filter(f => f.search_name.includes(q) || f.name_sr.toLowerCase()
    .replace(/[čć]/g,'c').replace(/š/g,'s').replace(/ž/g,'z').replace(/đ/g,'dj').includes(q)
  ).slice(0, 30)
}
